name: Build and Release

on:
  push:
    branches:
      - "*"
    tags:
      - "v?[0-9]*"
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      actions: read
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          push: false
          file: build.Dockerfile
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=local,dest=build

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: asn1scc.linux.x86_64.zip
          path: build/asn1scc.linux.x86_64.zip

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: asn1scc.windows.x86_64.zip
          path: build/asn1scc.windows.x86_64.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: build/*
          fail_on_unmatched_files: true
          generate_release_notes: true
          make_latest: true

      - name: Attest
        uses: actions/attest-build-provenance@v2
        if: github.ref_type == 'tag'
        with:
          subject-path: 'build/*'
